### ISSUE TITLE
Doesn't work to remove flowcell with command cgstats delete

### ISSUE THREAD

**Issue by moahaegglund** [Clinical-Genomics/cgstats#32]
Running the command `cgstats delete -f HLMHHDRXY` doesn't work. This is an SP flowcell with NIPT samples.
Error message:
```
[0|0|0] 9d/2z [hiseq.clinical@hasta:/home/proj/production] [P_main] 2s 148 $ cgstats delete -f HLMHHDRXY
Are you sure you want to delete [<Flowcell(flowcell_id=2499, flowcellname='HLMHHDRXY', flowcell_pos='A', hiseqtype='novaseq', time=datetime.datetime(2021, 11, 25, 23, 20, 25))>]? [y/N]: y
Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1480, in _object_value_for_elem
    return self._object_lookup[elem]
KeyError: 'csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/proj/bin/conda/envs/P_demux/bin/cgstats", line 10, in <module>
    sys.exit(root())
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hiseq.clinical/.local/lib/python3.7/site-packages/cgstats/db/cli.py", line 204, in delete
    manager.delete(rs)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/alchy/manager.py", line 85, in delete
    self.delete(*instance)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/alchy/manager.py", line 87, in delete
    self.session.delete(instance)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1967, in delete
    self._delete_impl(state, instance, head=True)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1994, in _delete_impl
    state.manager.mapper.cascade_iterator("delete", state)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/orm/mapper.py", line 3015, in cascade_iterator
    halt_on,
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1648, in cascade_iterator
    state, dict_, self.key, passive=passive
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/orm/relationships.py", line 1621, in _value_as_iterable
    x = impl.get(state, dict_, passive=passive)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 674, in get
    value = self.callable_(state, passive)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 708, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 798, in _emit_lazyload
    session.query(self.mapper), primary_key_identity
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/ext/baked.py", line 548, in _load_on_pk_identity
    result = list(bq.for_session(self.session).params(**params))
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 105, in instances
    util.raise_from_cause(err)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 277, in reraise
    raise value
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 85, in instances
    rows = [proc(row) for row in fetch]
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 85, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 572, in _instance
    populators,
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/orm/loading.py", line 693, in _populate_full
    dict_[key] = getter(row)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1566, in process
    value = self._object_value_for_elem(value)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/dialects/mysql/enumerated.py", line 147, in _object_value_for_elem
    return super(ENUM, self)._object_value_for_elem(elem)
  File "/home/proj/bin/conda/envs/P_demux/lib/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1483, in _object_value_for_elem
    '"%s" is not among the defined enum values' % elem
LookupError: "csv" is not among the defined enum values
```

**Comment by moahaegglund** [comment]
@karlnyr @patrikgrenfeldt I will tag you here as I know you had a quick look at this before the weekend. Do you have anything to add? Was is something about values that aren't allowed in cgstats?

**Comment by karlnyr** [comment]
Yes, "csv" needs to be added to the DataSource class here: https://github.com/Clinical-Genomics/cgstats/blob/master/cgstats/db/models.py
